name: Build Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
          submodules: 'recursive'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100

      - name: Download Setup Tool
        run: Invoke-WebRequest https://github.com/Personal-Cloud/PersonalCloudSetup/releases/download/1.2.7/PersonalCloudSetup.zip -Out .\PersonalCloudSetup.zip

      - name: Extract Setup Tool
        run: Expand-Archive -Path .\PersonalCloudSetup.zip -DestinationPath .\PersonalCloudSetup

      - name: Get Version String
        uses: frabert/replace-string-action@master
        id: get-version-string
        with:
          pattern: '^v(.*)$'
          string: "${{ github.event.release.tag_name }}"
          replace-with: '$1'
          flags: 'g'

      - name: Build ImageIndexer
        run: dotnet publish PersonalCloud.Core\src\Apps\Album\ImageIndexer\ImageIndexer.csproj -c Release -o .\PersonalCloudSetup\Data\ImageIndexer\ -r win-x86 --self-contained
        
      - name: Build AlbumApp
        run: dotnet build PersonalCloud.Core\src\Apps\Album\AlbumApp\AlbumApp.csproj -c Release -o .\PersonalCloudSetup\Data\AlbumApp\

      - name: Build Service (x86)
        run: dotnet publish Service\WindowsService.csproj -c Release -o .\PersonalCloudSetup\Data\Service\x86 -r win-x86 --self-contained

      - name: Build Service (x64)
        run: dotnet publish Service\WindowsService.csproj -c Release -o .\PersonalCloudSetup\Data\Service\x64 -r win-x64 --self-contained
        
      - name: Build Configurator
        run: dotnet publish Configurator\WindowsConfigurator.csproj -c Release -o .\PersonalCloudSetup\Data\GUI\ -r win-x86 --self-contained
        
      - name: Copy ImageIndexer and AlbumApp
        run: |
            Copy-Item -Path .\PersonalCloudSetup\Data\ImageIndexer\ -Filter *.* -Destination .\PersonalCloudSetup\Data\Service\x86\Apps\Album\ -Recurse
            Copy-Item -Path .\PersonalCloudSetup\Data\ImageIndexer\ -Filter *.* -Destination .\PersonalCloudSetup\Data\Service\x64\Apps\Album\ -Recurse
            Copy-Item -Path .\PersonalCloudSetup\Data\AlbumApp\* -Filter *.* -Destination .\PersonalCloudSetup\Data\Service\x86\Apps\Album\ -Recurse -Force
            Copy-Item -Path .\PersonalCloudSetup\Data\AlbumApp\* -Filter *.* -Destination .\PersonalCloudSetup\Data\Service\x64\Apps\Album\ -Recurse -Force
        
      - name: Move ffmpeg
        run: |
            Move-Item -Path .\PersonalCloudSetup\Data\ffmpeg_bin\x86\ffmpeg.exe -Destination .\PersonalCloudSetup\Data\Service\x86\Apps\Album\ffmpeg.exe
            Move-Item -Path .\PersonalCloudSetup\Data\ffmpeg_bin\x64\ffmpeg.exe -Destination .\PersonalCloudSetup\Data\Service\x64\Apps\Album\ffmpeg.exe
        
      - name: Generate Setup Files
        run: .\PersonalCloudSetup\PersonalCloudSetup.exe -d .\PersonalCloudSetup\Data -b "${{ steps.get-version-string.outputs.replaced }}"
        
      - name: Create Zip File
        run: |
            Compress-Archive -Path .\PersonalCloudSetup\PersonalCloud-${{ steps.get-version-string.outputs.replaced }}-x86.exe -DestinationPath .\PersonalCloudSetup\PersonalCloud-${{ steps.get-version-string.outputs.replaced }}-x86-with-dokan.zip
            Compress-Archive -Path .\PersonalCloudSetup\PersonalCloud-${{ steps.get-version-string.outputs.replaced }}-x86.msi -DestinationPath .\PersonalCloudSetup\PersonalCloud-${{ steps.get-version-string.outputs.replaced }}-x86-no-dokan.zip
            Compress-Archive -Path .\PersonalCloudSetup\PersonalCloud-${{ steps.get-version-string.outputs.replaced }}-x64.exe -DestinationPath .\PersonalCloudSetup\PersonalCloud-${{ steps.get-version-string.outputs.replaced }}-x64-with-dokan.zip
            Compress-Archive -Path .\PersonalCloudSetup\PersonalCloud-${{ steps.get-version-string.outputs.replaced }}-x64.msi -DestinationPath .\PersonalCloudSetup\PersonalCloud-${{ steps.get-version-string.outputs.replaced }}-x64-no-dokan.zip

      - name: Upload Setup (32-bit EXE)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .\PersonalCloudSetup\PersonalCloud-${{ steps.get-version-string.outputs.replaced }}-x86-with-dokan.zip
          asset_name: PersonalCloud-${{ steps.get-version-string.outputs.replaced }}-x86-with-dokan.zip
          asset_content_type: application/octet-stream
          
      - name: Upload Setup (32-bit MSI)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .\PersonalCloudSetup\PersonalCloud-${{ steps.get-version-string.outputs.replaced }}-x86-no-dokan.zip
          asset_name: PersonalCloud-${{ steps.get-version-string.outputs.replaced }}-x86-no-dokan.zip
          asset_content_type: application/octet-stream
        
      - name: Upload Setup (64-bit EXE)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .\PersonalCloudSetup\PersonalCloud-${{ steps.get-version-string.outputs.replaced }}-x64-with-dokan.zip
          asset_name: PersonalCloud-${{ steps.get-version-string.outputs.replaced }}-x64-with-dokan.zip
          asset_content_type: application/octet-stream
          
      - name: Upload Setup (64-bit MSI)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .\PersonalCloudSetup\PersonalCloud-${{ steps.get-version-string.outputs.replaced }}-x64-no-dokan.zip
          asset_name: PersonalCloud-${{ steps.get-version-string.outputs.replaced }}-x64-no-dokan.zip
          asset_content_type: application/octet-stream
